name: ci

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/55 */6  * * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
  
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Auto green
        run: |
          git config --local user.email "wula248508@gmail.com"
          git config --local user.name "wula248508"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "乌拉~乌拉~"
          git push
